#server:
#  port: 8087
#  servlet:
#    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
#  datasource:
#    url:  jdbc:postgresql://localhost:5432/ead-authuser-v2
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#   ansi:
#     enabled: always
#  rabbitmq:
#    addresses: amqps://zjxwabag:SKvK6q_BEFGfuOxIe1F2AUs33sHFBUaW@armadillo.rmq.cloudamqp.com/zjxwabag
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  api:
#    url:
#      course: 'http://ead-course-service/ead-course'
#  broker:
#    exchange:
#      userEvent: ead.userevent
#
#eureka:
#  client:
#    service-url:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      circuibreakerInstance:
#        sliding-window-type: time_based
#        minimum-number-of-calls: 2
#        failure-rate-threshold: 80
#        sliding-window-size: 30
#        permitted-number-of-calls-in-half-open-state: 2
#        wait-duration-in-open-state: 30s
##  retry:
##    instances:
##      retryInstance:
##        max-attempts: 3
##        wait-duration: 5s